### ISSUE TITLE
Crash in IDEA 2022.2.3

### ISSUE THREAD

**Issue by robertoschwald** [Fapiko/intellij-better-direnv#18]
java.lang.NoClassDefFoundError: com/intellij/sh/SHIcons
	at com.fapiko.jetbrains.plugins.better_direnv.language.filetype.DirenvFileType.getIcon(DirenvFileType.java:38)

Seems it needs adaption to the new IDEA version.

**Comment by apane-tackle** [comment]
This is a duplicate of https://github.com/Fapiko/intellij-better-direnv/issues/16

**Comment by jakul** [comment]
@Fapiko Hi 👋🏽

I'd like to try out your plugin but I cannot as it doesn't work with the latest version of PyCharm, due to this issue 👆🏽

Could you cut a new version that includes the fix please?

Thanks,
Craig
