### ISSUE TITLE
python support

### ISSUE THREAD

**Issue by sertaco** [Fapiko/intellij-better-direnv#3]
Python support much appreciated. 

If you can show some pointers, I can give it a try too

**Comment by Fapiko** [comment]
Hey @sertaco - I think Python support should be fairly straightforward, I've just been swamped for the past month or so.

If you take a look at how the `EnvFile` plugin is handling it https://github.com/ashald/EnvFile/blob/develop/modules/products/pycharm/src/main/java/net/ashald/envfile/products/pycharm/PyCharmRunConfigurationExtension.java should give a baseline for how to adapt this plugin.

The trickiest part for me was probably the build system if you're not super familiar with Gradle (I mostly used maven when I was doing Java development on a daily basis). If you take a look at this PR diff you can see the changes I made to integrate with Go and Node run configs: https://github.com/Fapiko/intellij-better-direnv/commit/6aaaea87a418338ee3870f852d2195a5db2d85cb#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06

**Comment by jfreela** [comment]
Just pushed a PR for this - https://github.com/Fapiko/intellij-better-direnv/pull/6

**Comment by Fapiko** [comment]
This is in the latest release 0.3.0 - should be verified and available in a day or two.

**Comment by sertaco** [comment]
I had a chance to try 0.3.0 today and could not make it work. Did anyone use Python direnv succesfully?

**Comment by Fapiko** [comment]
I'm actually noticing that this doesn't work on versions 2022.2 and newer, but does on 2022.1. So something has changed with the Python plugin execution path.

**Comment by jfreela** [comment]
Added PR to address broken Python support in IDEA 2022.2+

https://github.com/Fapiko/intellij-better-direnv/pull/9

**Comment by sertaco** [comment]
perfect! works as expected for 2022.2.1! thanks
